package:
  name: amass
  version: 3.23.2
  epoch: 0
  description: "attack surfaces and external asset discovery tools set"
  copyright:
    - license: Apache-2.0
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - go
pipeline:
  - uses: go/install
    with:
      package: github.com/owasp-amass/amass/v3/...
      version: v${{package.version}}
  - uses: strip
