package:
  name: exploitdb
  version: 2023-08-05
  epoch: 0
  description: "the exploit database is an archive of public exploits and corresponding vulnerable software, developed for use by penetration testers and vulnerability researchers"
  copyright:
    - license: GPL-2.0
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - git
      - wolfi-base
pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/exploit-database/exploitdb.git
      branch: ${{package.version}}
      destination: exploitdb
  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/share/app/exploitdb && mkdir -p "${{targets.destdir}}"/usr/bin
      mv exploitdb/* exploitdb/.searchsploit_rc "${{targets.destdir}}"/usr/share/app/exploitdb
     
      sed -i 's/\/opt\/exploitdb/\/usr\/share\/app\/exploitdb/g' "${{targets.destdir}}"/usr/share/app/exploitdb/.searchsploit_rc

      ln -sf /usr/share/app/exploitdb/searchsploit "${{targets.destdir}}"/usr/bin
  - uses: strip
