package:
  name: gobuster
  version: 3.5.0
  epoch: 0
  description: "a tool used to brute force attack"
  copyright:
    - license: Apache-2.0
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - go
pipeline:
  - uses: go/install
    with:
      package: github.com/OJ/gobuster/v3
      version: v${{package.version}}
  - uses: strip
