package:
  name: jwt-tool
  version: 2.2.6
  epoch: 0
  description: "toolkit for validating, forging, scanning and tampering JWTs"
  copyright:
    - license: GPL-3.0
  dependencies:
    runtime:
      - python3
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - python3
      - py3-pip
      - wolfi-base
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ticarpi/jwt_tool
      branch: v${{package.version}}
      destination: jwt-tool
  - runs: |
      mkdir -p ${{targets.destdir}}/opt/venvs/jwt-tool

      mv jwt-tool ${{targets.destdir}}/opt/venvs && cd ${{targets.destdir}}/opt/venvs/jwt-tool

      pip3 install pipenv
      export PIPENV_VENV_IN_PROJECT=1
      pipenv install termcolor cprint pycryptodomex requests

      JWT_TOOL_PYTHON_PATH="#!/opt/venvs/jwt-tool/.venv/bin/python"
      sed -i "1s,.*,$JWT_TOOL_PYTHON_PATH," jwt_tool.py

      chmod +x jwt_tool.py

      mkdir -p ${{targets.destdir}}/usr/bin && ln -s /opt/venvs/jwt-tool/jwt_tool.py ${{targets.destdir}}/usr/bin/jwt-tool
  - uses: strip
