package:
  name: nmap
  version: 7.94
  epoch: 0
  description: "network discovery and security auditing tool"
  copyright:
    - license: GPL-2.0
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-base
      - build-base
      - openssl-dev
pipeline:
  - uses: fetch
    with:
      uri: https://nmap.org/dist/nmap-${{package.version}}.tar.bz2
      expected-sha256: d71be189eec43d7e099bac8571509d316c4577ca79491832ac3e1217bc8f92cc
  - uses: autoconf/configure
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
  - runs: |
      # nmap require cap_net_raw,cap_net_admin,cap_net_bind_service+eip while working nonroot
      # capabilities can define but they don't pass to container.
      # suid defined
      chmod 4755 ${{targets.destdir}}/usr/bin/nmap
  - uses: strip
