package:
  name: semgrep
  version: 1.15.0
  epoch: 0
  description: "static code analysis tool"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3
      - py3-pip

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-base
      - ca-certificates-bundle
      - python3
      - py3-pip

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/9d/e7/5a31be69c8dc355aee831e0a282bbc39ec3f31ebfcd5d5a7b3fab514e13e/semgrep-${{package.version}}-cp37.cp38.cp39.py37.py38.py39-none-any.whl
      expected-sha256: b55392f912ee9fb6fb803086c251d9c37fdfd54ab9be14e0447d89ff2da79411
      extract: false
  - runs: |
      pip3 install --prefix=/usr --root="${{targets.destdir}}" semgrep-${{package.version}}-cp37.cp38.cp39.py37.py38.py39-none-any.whl
  - uses: strip

