package:
  name: semgrep
  version: 1.22.0
  epoch: 0
  description: "lightweiight static code analysis tool"
  copyright:
    - license: LGPL-2.1
  dependencies:
    runtime:
      - python3
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - python3
      - py3-pip
      - wolfi-base
pipeline:
  - runs: |
      mkdir -p ${{targets.destdir}}/opt/venvs/semgrep && cd ${{targets.destdir}}/opt/venvs/semgrep

      pip3 install pipenv
      export PIPENV_VENV_IN_PROJECT=1
      pipenv install semgrep==${{package.version}}

      SEMGREP_PYTHON_PATH="#!/opt/venvs/semgrep/.venv/bin/python"
      sed -i "1s,.*,$SEMGREP_PYTHON_PATH," .venv/bin/semgrep

      mkdir -p ${{targets.destdir}}/usr/bin && ln -s /opt/venvs/semgrep/.venv/bin/semgrep ${{targets.destdir}}/usr/bin/semgrep
  - uses: strip
