package:
  name: sqlmap
  version: 1.7.5
  epoch: 0
  description: "a tool that automates the process of detecting and exploiting SQL injection flaws"
  copyright:
    - license: GPL-2.0
  dependencies:
    runtime:
      - python3
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - python3
      - wolfi-base
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sqlmapproject/sqlmap
      branch: ${{package.version}}
      destination: sqlmap
  - runs: |
      mkdir -p ${{targets.destdir}}/opt/venvs/sqlmap
      mv sqlmap ${{targets.destdir}}/opt/venvs && cd ${{targets.destdir}}/opt/venvs/sqlmap
      mkdir -p ${{targets.destdir}}/usr/bin && ln -s /opt/venvs/sqlmap/sqlmap.py ${{targets.destdir}}/usr/bin/sqlmap
  - uses: strip
