name: build-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    name: Build Security Tool Box
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      
      - uses: chainguard-dev/actions/setup-melange@main
      
      - uses: chainguard-dev/actions/melange-keygen@main
        with:
          signing-key-path: ${{ github.workspace }}/melange.rsa
          install-public-key: true
      
      - shell: bash
        run: |
          ls ${{ github.workspace }}
          
      - uses: chainguard-dev/actions/melange-build-pkg@main
        with: 
          config: tools/checkov.yaml
          archs: x86_64
          signing-key-path: ${{ github.workspace }}/melange.rsa
          repository-path: ${{ github.workspace }}/packages
      
      - uses: chainguard-dev/actions/melange-build-pkg@main
        with: 
          config: tools/semgrep.yaml
          archs: x86_64
          signing-key-path: ${{ github.workspace }}/melange.rsa
          repository-append: ${{ github.workspace }}/packages
          
      - uses: chainguard-dev/actions/apko-build@main
        with:
          config: apko.yaml
          tag: ghcr.io/ahmetak4n/security-tool-box:latest



