name: build-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:

  red-build:
    name: stb red
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - name: checkot repository
        uses: actions/checkout@v3
        
      - name: build apk packages
        uses: chainguard-dev/actions/melange-build@main
          
      - name: build and push image
        uses: distroless/actions/apko-publish@main
        with:
          config: stb-red.yaml
          archs: x86_64
          tag: ghcr.io/ahmetak4n/security-tool-box:stb-red
          repository-append: packages
          keyring-append: melange.rsa.pub
          use-docker-mediatypes: false

  green-build:
    name: stb green
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - name: checkot repository
        uses: actions/checkout@v3
        
      - name: build apk packages
        uses: chainguard-dev/actions/melange-keygen@main
        
      - name: build and push image
        uses: distroless/actions/apko-publish@main
        with:
          config: stb-green.yaml
          archs: x86_64
          tag: ghcr.io/ahmetak4n/security-tool-box:stb-green
          repository-append: packages
          keyring-append: melange.rsa.pub
          use-docker-mediatypes: false


