name: build-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  
  build:
    name: Build APK Package
    runs-on: ubuntu-latest
    
    container: cgr.dev/chainguard/melange

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3
      
      - name: Melange Key Generation
        run: |
          melange keygen
          
          ls -al
      
