name: build-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  
  build:
    name: build and push
    runs-on: ubuntu-latest

    steps:
      - name: checkot repository
        uses: actions/checkout@v3
      
      - name: setup melange
        uses: chainguard-dev/actions/setup-melange@main
      
      - name: melange key generation
        uses: chainguard-dev/actions/melange-keygen@main
        with:
          signing-key-path: ${{ github.workspace }}/melange.rsa
          install-public-key: true
          
      - name: melange apk build
        shell: bash
        run: |
          melange build tools/semgrep.yaml --arch amd64 --signing-key melange.rsa
          melange build tools/checkov.yaml --arch amd64 --signing-key melange.rsa --repository-append packages
          
          ls
