name: Build 

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/*'
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - name: checkot repository
        uses: actions/checkout@v3
      
      - name: apko build
        shell: bash
        run : |
          docker run -i --rm --entrypoint /bin/sh \
          -v $PWD:${{ github.workspace }} --workdir ${{ github.workspace }} \
        ghcr.io/wolfi-dev/apko:latest build stb-green.yaml stb-green:test stb-green.tar

        #      - name: green build and push image
        #        uses: distroless/actions/apko-snapshot@main
        #        with:
        #          config: stb-green.yaml
        #          archs: amd64
        #          base-tag: ghcr.io/ahmetak4n/security-tool-box 
        #          target-tag: stb-green-${{ github.sha }}
