name: Build 

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/*'
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - name: checkot repository
        uses: actions/checkout@v3
      
      - name: green build image
        uses: distroless/actions/apko-build@main
          with:
            config: stb-green.yaml
            archs: amd64, arm64, x86_64
            base-tag: ghcr.io/ahmetak4n/security-tool-box/stb-green-${{ github.sha }} 
