name: build-ci

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/*'
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:

  green-build:
    name: stb green
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - name: checkot repository
        uses: actions/checkout@v3
      
      - name: Print new build number
        run: |
          ls -al /etc/apk/keys/
          sudo mkdir -p /etc/apk/keys
        
      - name: build apk packages
        uses: chainguard-dev/actions/melange-build@main
        with:
          config: ''
          multi-config: ${{ github.workspace }}/tools/semgrep.yaml 
          archs: x86_64
          signing-key-path: ${{ github.workspace }}/melange.rsa
          repository-path: ${{ github.workspace }}/packages
          repository-append: ${{ github.workspace }}/packages
          keyring-append: ''
          namespace: ''
          empty-workspace: false
          workdir: ''
        
      - name: build and push image
        uses: distroless/actions/apko-publish@main
        with:
          config: stb-green.yaml
          archs: x86_64
          tag: ghcr.io/ahmetak4n/security-tool-box:stb-green
          repository-append: packages
          keyring-append: melange.rsa.pub
          use-docker-mediatypes: false


