name: Build 

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/*'
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - name: checkot repository
        uses: actions/checkout@v3
      - name: apko build
        run: |
          docker run --rm \
            -v $PWD:${{ github.workspace }} \
            -v /tmp:/tmp \
            ghcr.io/wolfi-dev/apko:latest build ghcr.io/ahmetak4n/security-tool-box/stb-green-${{ github.sha }} stb-green-output.tar
          docker load < stb-green-output.tar
          docker push ghcr.io/ahmetak4n/security-tool-box/stb-green-${{ github.sha }}

        # - name: green build image
          #   uses: distroless/actions/apko-build@main
          #   with:
          #     config: stb-green.yaml
          #     archs: amd64,arm64,x86_64
          #     tag: ghcr.io/ahmetak4n/security-tool-box/stb-green-${{ github.sha }} 
