name: build-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  
  build:
    name: Build APK Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: chainguard-dev/actions/setup-melange@main
      
      - uses: chainguard-dev/actions/melange-keygen@main
        with:
          signing-key-path: ${{ github.workspace }}/melange.rsa
          install-public-key: true
          
      - name: ASDF
        shell: bash
        run: |
          melange build tools/semgrep.yaml --arch amd64 --signing-key melange.rsa
          
          ls -al
