name: Release

on:
  release:
    types: [ created ]
  
  workflow_dispatch:  

jobs:

  build:
    name: Release
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkot Repository
        uses: actions/checkout@v3

      - name: Cosign Install
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: 'v2.1.1'
      
      - name: Login GCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Stb Green Apko Build & Docker Push
        run: |
          docker run --rm \
            -v $PWD:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            ghcr.io/wolfi-dev/apko:latest build stb-green.yaml --arch arm64,amd64 ghcr.io/ahmetak4n/security-tool-box:stb-green-demo stb-green-output.tar
          docker load < stb-green-output.tar
          docker tag  ghcr.io/ahmetak4n/security-tool-box:stb-green-demo-amd64 ghcr.io/ahmetak4n/security-tool-box:stb-green-demo  
          docker push --all-tags ghcr.io/ahmetak4n/security-tool-box
          DIGEST=(docker inspect --format='{{.RepoDigests}}' ghcr.io/ahmetak4n/security-tool-box:stb-green-demo)
          DIGEST=(docker inspect --format='{{.RepoDigests}}' ghcr.io/ahmetak4n/security-tool-box:stb-green-demo-arm64)
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${DIGEST}"
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Stb Red Apko Build & Docker Push
        run: |
          docker run --rm \
            -v $PWD:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            ghcr.io/wolfi-dev/apko:latest build stb-red.yaml --arch arm64,amd64 ghcr.io/ahmetak4n/security-tool-box:stb-red-${{github.ref_name}} stb-red-output.tar
          docker load < stb-red-output.tar
          docker push --all-tags ghcr.io/ahmetak4n/security-tool-box 
